"use client"
//import type { Metadata } from "next";
import {useEffect} from 'react';
import {API} from '@/app/account/client';
import  Geist   from 'next/font/local'; // "next/font/google";
import    Geist_Mono   from 'next/font/local';
import addInterceptor from '@/app/account_interceptor';
import "./globals.css";

import "./preloader.css";
import Script from 'next/script';
let subArray:any[] =["latin"];
let  fntgeistsans:any = "--font-geist-sans"
let  fntgeistmono:any = "--font-geist-mono"
const geistSans = Geist({
  variable: "--font-geist-sans",  src: "./fonts/Geist-Regular.ttf" //"latin"//,subArray ${process.env.FYERS_BASE_URI}
 // subsets: subArray //["latin"],
});

const geistMono = Geist_Mono({
  variable:"--font-geist-mono",
  src:  "./fonts/GeistMono-Regular.ttf" //"latin" //[],subArray
});
/*  bellow does not support use client
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

      useEffect(() => {
        addInterceptor(API)
    }, [])

  return (
    <html lang="en">
        {/* Include the external script */}
      <Script 
        src="/bundles/runtime.0716c8089d42c5b9ea4c.js" 
        onLoad={() => {
          console.log('Script runtime.0716c8089d42c5b9ea4c.js loaded successfully!');
        }}
      />
        <Script 
        src="/bundles/en.7249.ae315255b77fb4a87e60.js" 
        onLoad={() => {
          console.log('Script bundles/en.7249.ae315255b77fb4a87e60.js loaded successfully!');
        }}
      />
      <Script 
        src="/bundles/2614.3c6e9a4d2c016c8e0d98.js" 
        onLoad={() => {
          console.log('Script bundles/2614.3c6e9a4d2c016c8e0d98.js loaded successfully!');
        }}
      />
      {/* <Script 
        src="/bundles/library.0f032f79907a36608fbe.js" 
        onLoad={() => {
          console.log('Script bundles/library.0f032f79907a36608fbe.js loaded successfully!');
        }}
      /> */}
      <Script 
        src="https://d2r1yp2w7bby2u.cloudfront.net/js/clevertap.min.js" 
        onLoad={() => {
          console.log('Script https://d2r1yp2w7bby2u.cloudfront.net/js/clevertap.min.jsloaded successfully!');
        }}
      />
      <Script 
        src="https://trade.fyers.in/static/js/loader/2.1/loader.min.js" 
        onLoad={() => {
          console.log('Script https://trade.fyers.in/static/js/loader/2.1/loader.min.js loaded successfully!');
        }}
      />
      <Script 
        src="/bundles/runtime.0716c8089d42c5b9ea4c.js" 
        onLoad={() => {
          console.log('Script runtime.0716c8089d42c5b9ea4c.js loaded successfully!');
        }}
      />
      <Script 
        src="/bundles/runtime.0716c8089d42c5b9ea4c.js" 
        onLoad={() => {
          console.log('Script runtime.0716c8089d42c5b9ea4c.js loaded successfully!');
        }}
      />
            <link rel="stylesheet" type="text/css" href="/css/2666.d7dd4a59f33a2f52cf86.css" precedence="default"></link>
            {/* https://assets.fyers.in/tv_lib/v29.5.0_unmodified/bundles/empty-coin-light.6d0b731ac6f489f06e65.svg  */}
        <link type="text/css" href="/bundles/4986.8b484bfeff805649f879.css" rel="stylesheet"  precedence="default"/>
         <link rel="stylesheet" href="/css/preloader.css" precedence="default" />
        	<link rel="stylesheet" href="https://trade.fyers.in/lib/bootstrap/4/bootstrap-float-label.min.css" precedence="default"  />
		<link rel="stylesheet" href="https://trade.fyers.in/Prod/1.2/global-header.css" precedence="default" />
		<link rel="stylesheet" href="/css/2092.4b97d1e084a7f81e17f2.css" precedence="default" />
		<link href="https://assets.fyers.in/Lib/googleapis/css2.css?family=Poppins:wght@200;300;400;500;600;700&amp;display=swap" rel="stylesheet" precedence="default"  />
		
		<link href="https://trade.fyers.in/Prod/1.2/position.css?v=1.1" rel="stylesheet" precedence="default"  />
		
		<link href="https://trade.fyers.in/static/js/logoutModel/style/logout.css" rel="stylesheet"  precedence="default" />
		
		<link rel="stylesheet" href="https://trade.fyers.in/production/v1.1/fyers-ui.css?v=1.2" precedence="default"  />
		
		<link rel="stylesheet" href="https://trade.fyers.in/Prod/1.2/bubble.css" precedence="default" />
		
		<link rel="stylesheet" href="https://trade.fyers.in/Prod/1.2/fyers-widget.css?v=1.1" precedence="default"  />
		<link href="https://trade.fyers.in/Prod/1.2/option-chain.css" rel="stylesheet" precedence="default" ></link>









      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
